### ISSUE TITLE
Sum of PV1 power and PV2 power

### ISSUE THREAD

**Issue by kamransaleem** [kellerza/sunsynk#102]
Existing sensor definitions can be found [here](https://github.com/kellerza/sunsynk/blob/main/sunsynk/definitions.py)

### You Inverter

Sunsynk 8kw

### Describe the issue/bug and what you expect

A sum of pv1 and pv2 power so that I can create automations based on the combined power generated

**Comment by jabezz** [comment]
You can do this in Home Assistant.

Add some template sensors in your configuration.yaml


```
template:
  - sensor:
      - name: "Total Solar Power"
        unit_of_measurement: 'W'
        state: >
          {{ (states("sensor.ss_pv1_power") | float + states("sensor.ss_pv2_power") | float) | round(2) }}
        device_class: power
        state_class: measurement
  - sensor:
      - name: "Total Solar Current"
        unit_of_measurement: 'A'
        state: >
          {{ (states("sensor.ss_pv1_current") | float + states("sensor.ss_pv2_current") | float) | round(2) }}
        device_class: current
        state_class: measurement
  - sensor:
      - name: "Total Solar Voltage"
        unit_of_measurement: 'V'
        state: >
          {{ (states("sensor.ss_pv1_voltage") | float + states("sensor.ss_pv2_voltage") | float) | round(2) }}
        device_class: voltage
        state_class: measurement

```

reboot and voila.

**Comment by kamransaleem** [comment]
that worked great, thank you

**Comment by BrendanW74** [comment]
> that worked great, thank you

Hi there kamransaleem

I was wondering if you could please help. I have been trying to get the above to work in HA for the past 3 days now.

The code is not the problem, I literally copied/pasted it into my "configuration.yaml" file, and ran the "CHECK CONFIGURATION" option under dev tools, and it states "Configuration will not prevent Home Assistant from starting!".

Once this has been added, where/how do you gain access to the PV1+PV2 result?
I am not sure where I am able to use the combined information within HA.

Any help would be most appreciated.
Thank you in advance.

**Comment by jabezz** [comment]
The Entity will be available to add to any card.

![image](https://user-images.githubusercontent.com/319878/222925608-7f62b835-286d-4c18-b3d5-ac2e19270b7c.png)
![image](https://user-images.githubusercontent.com/319878/222925621-355b61a0-45af-4d7c-9f77-aba9525eea37.png)

or 

```
type: entities
entities:
  - entity: sensor.total_solar_power
    name: Solar Power
```
or
![image](https://user-images.githubusercontent.com/319878/222925685-dbf8455c-9caf-46a8-93c0-0c4635e301b6.png)
![image](https://user-images.githubusercontent.com/319878/222925707-ba698820-8a86-41f2-a68b-4f5b45fa9fce.png)

you can also check the values in Developer Tools
![image](https://user-images.githubusercontent.com/319878/222925749-6f159a48-cf8d-4fd4-940d-176f8e70bde8.png)
