### ISSUE TITLE
Multi Version - Direct serial interface

### ISSUE THREAD

**Issue by cakuhn** [kellerza/sunsynk#131]
HI

On the latest version, installed this morning (Sunsynk Inverter Add-on (multi): Current version: 2023.04.20b-0.3.2 (Changelog)) I get the below errors as reported in the log.  The application then crash.  Any ideas on a possible fix and the reason for these?

Thanks

2023-04-21 07:32:39,121 ERROR   Read Error: <class 'Exception'>: (1,59,1) 'Serial' object has no attribute 'host'
2023-04-21 07:32:52,742 ERROR   Read Error: <class 'Exception'>: (1,268,6) 'Serial' object has no attribute 'host'
2023-04-21 07:33:03,835 ERROR   Read Error: <class 'Exception'>: (1,59,1) 'Serial' object has no attribute 'host'
2023-04-21 07:33:18,948 ERROR   Read Error: <class 'Exception'>: (1,59,1) 'Serial' object has no attribute 'host'
2023-04-21 07:34:38,121 ERROR   Read Error: <class 'Exception'>: (1,78,1) 'Serial' object has no attribute 'host'

**Comment by kellerza** [comment]
Can you try the **pymodbus** driver?

**Comment by kellerza** [comment]
@cakuhn can you try these options?

The actual value of the port below you can get from the `DEBUG_DEVICE` field in the UI (at the bottom of the settings)

1. Direct Serial + pymodbus
    ```yaml
    DRIVER: pymodbus
    INVERTERS:
      - PORT: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A9007CPR-if00-port0
    ```

2. Direct serial + umodbus
    ```yaml
    DRIVER: umodbus
    INVERTERS:
      - PORT: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A9007CPR-if00-port0
    ```

3. umodbus via mbusd (and mbusd to serial)
    This will work, but won't help me to test the serial implementation
