### ISSUE TITLE
config for multiple inverters

### ISSUE THREAD

**Issue by richjgould** [kellerza/sunsynk#188]
Just had a Sunsynk 8.8kw inverter installed in parallel to my existing 3.6kw. Add-on was working fine with just the 3.6kw.

Can I clarify if this config is correct:

```
- SERIAL_NR: "2205xxxxxx"
  HA_PREFIX: 3K6
  MODBUS_ID: 1
  PORT: tcp://homeassistant.local:502
  
- SERIAL_NR: "2304xxxxxx"
  HA_PREFIX: 8K8
  MODBUS_ID: 2
  PORT: tcp://homeassistant.local:502
```
I have set the inverters as master/slave on the devices and the Modbus ports to match. Cat5 cable between the parallel sockets of the inverters.

Thanks
Richard

**Comment by richjgould** [comment]
Is there anywhere else I could be signposted for further advice or examples of this running on the multi-inverter add-on?

I now have a RS485 adaptor per inverter.

Is the config below correct when dealing with multiple RS485 adaptors in once instance of the add-on?

`
- SERIAL_NR: "220528xxxx"
  HA_PREFIX: 3k6
  MODBUS_ID: 1
  PORT: tcp://homeassistant.local:502
  DEVICE: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5185022356-if00

- SERIAL_NR: "230405xxxx"
  HA_PREFIX: 8k8
  MODBUS_ID: 2
  PORT: tcp://homeassistant.local:502
  DEVICE: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5586009732-if00
`

Thanks
Richard

**Comment by richjgould** [comment]
Is there anywhere else I could be signposted for further advice or examples of this running on the multi-inverter add-on?

I now have an RS485 adaptor per inverter.

Is the config below correct when dealing with multiple RS485 adaptors in once instance of the add-on?

```
- SERIAL_NR: "2205xxxx"
  HA_PREFIX: 3k6
  MODBUS_ID: 1
  PORT: tcp://homeassistant.local:502
  DEVICE: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5185022356-if00

- SERIAL_NR: "2304xxxx"
  HA_PREFIX: 8k8
  MODBUS_ID: 2
  PORT: tcp://homeassistant.local:502
  DEVICE: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5586009732-if00
```

Thanks
Richard

**Comment by kellerza** [comment]
```yaml
DRIVER: pymodbus
INVERTERS:
- SERIAL_NR: "2205xxxx"
  HA_PREFIX: 3k6
  MODBUS_ID: 1
  PORT: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5185022356-if00
- SERIAL_NR: "2304xxxx"
  HA_PREFIX: 8k8
  MODBUS_ID: 2
  PORT: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5586009732-if00
```
