### ISSUE TITLE
Python Error  

### ISSUE THREAD

**Issue by schpuntik** [kellerza/sunsynk#255]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue/bug

**Expected behavior**

### Your environment

- Home Assistant version: 2024.2.5
- Addon:
  - Name: sunsynk-multi
  - Version: 0.6.5
- Inverter:
  - Make: Deye
  - Model: SUN-5K-SG03LP1-EU
  - Firmware: \_\_
- Adaptor details:
  - RS485 to USB
 

### You configuration

```
DRIVER: pymodbus
INVERTERS:
  - SERIAL_NR: "24"
    HA_PREFIX: DI
    MODBUS_ID: 1
    DONGLE_SERIAL_NUMBER: "0"
    PORT: ""
SENSOR_DEFINITIONS: three-phase
SENSORS:
  - energy_management
  - power_flow_card
  - pv2_power
SENSORS_FIRST_INVERTER:
  - settings
MANUFACTURER: Deye
READ_ALLOW_GAP: 2
READ_SENSORS_BATCH_SIZE: 20
SCHEDULES:
  - KEY: W
    READ_EVERY: 5
    REPORT_EVERY: 60
    CHANGE_ANY: false
    CHANGE_BY: 80
    CHANGE_PERCENT: 0
NUMBER_ENTITY_MODE: auto
PROG_TIME_INTERVAL: 15

```

### Logs

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service legacy-services: starting
services-up: info: copying legacy longrun sunsynk (no readiness notification)
s6-rc: info: service legacy-services successfully started
22:47:11 INFO    Loading configuration: /data/options.json
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/ha_addon_sunsynk_multi/__main__.py", line 79, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/ha_addon_sunsynk_multi/__main__.py", line 61, in main
    init_options()
  File "/usr/local/lib/python3.11/site-packages/ha_addon_sunsynk_multi/options.py", line 95, in init_options
    unmarshal(OPT, opt)
  File "/usr/local/lib/python3.11/site-packages/ha_addon_sunsynk_multi/options.py", line 28, in unmarshal
    setattr(target, key, val)
AttributeError: 'Options' object has no attribute 'prog_time_interval'
[22:47:11] WARNING: Halt add-on with exit code 1
s6-rc: info: service legacy-services: stopping
s6-rc: info: service legacy-services successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped

```
