### ISSUE TITLE
grid_connected always OFF: Deye 3-phase

### ISSUE THREAD

**Issue by marekorok** [kellerza/sunsynk#277]
Existing sensor definitions can be found [here](https://github.com/kellerza/sunsynk/blob/main/src/sunsynk/definitions.py)

### Your Inverter
Deye SUN-10K-SG04LP3-EU

### Describe the issue/bug and what you expect
since the begging after setup the grid_connected always reports OFF, even I switch it manually in the mqtt it immediately turns off.
![image](https://github.com/kellerza/sunsynk/assets/28598034/93d2e9cc-fa96-484d-91d6-6c220716935a)

Other sensors looks fine, no idea how to fix it.

Using docker edge version:

```
# Deye/sunsynk
# ------------------------------------------------
  deye:
    container_name: deye
    restart: unless-stopped
    image: ghcr.io/kellerza/hass-addon-sunsynk-multi/armv7:edge
    volumes:
      - ./mounts/deye/options.yaml:/data/options.yaml
```

DRIVER: "solarman"

grid_connected included in config:
![image](https://github.com/kellerza/sunsynk/assets/28598034/5de06d4c-5b2b-4ee5-ab5a-720c17a39160)

No specific logs
