### ISSUE TITLE
Strange log entry after updating to 0.7.0

### ISSUE THREAD

**Issue by man55** [kellerza/sunsynk#338]
This is the entry that appeared in the log after updating to the latest version. This didn't happen before the update.

```
/usr/local/lib/python3.11/site-packages/ha_addon_sunsynk_multi/a_sensor.py:161: RuntimeWarning: coroutine 'ASensor.publish' was never awaited
  self.publish(val)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

config
```
DRIVER: umodbus
INVERTERS:
  - SERIAL_NR: "ххх"
    HA_PREFIX: DEYE
    MODBUS_ID: 1
    PORT: tcp://192.168.1.183:502
SENSOR_DEFINITIONS: single-phase
```
