### ISSUE TITLE
Grid Power showing incorrectly after Firmware upgrade.

### ISSUE THREAD

**Issue by Marzlio** [kellerza/sunsynk#343]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue/bug

After the firmware upgrade from version: 9.0.2.2 to 9.0.2.6 grid power is showing incorrectly.
I believe it is expecting WATTS and getting KW. But i could be wrong
when connecting to mbusd and checking the inverter values for 169, 168 and 168 i get the following 

```bash
Register 167 = 94
Register 168 = 0
Register 169 = 94
```
When checking on the inverter is was 940W 
Apologies in advance if i missed something obvious.

**Expected behaviour**

Not 100% sure but i think it needs to be multiplied by 10?

when i use the below it shows correctly

```yaml

  - platform: template
    sensors:
      sunsynk_grid_power_scaled:
        friendly_name: "Grid Power (Scaled)"
        unit_of_measurement: 'W'
        value_template: "{{ states('sensor.sunsynk_grid_power') | float * 10 }}"
```

### Your environment

- Home Assistant version: 2023.8.x
- Addon:
  - Name: sunsynk-multi
  - Version: 0.7.4
- Inverter:
  - Make: Sunsynk
  - Model: 16kW 1P
  - Firmware: 9.0.2.6
- Adaptor details:
  - RS485/RS232
