### ISSUE TITLE
SENSORS_FIRST_INVERTER creating same sef of entities on all inverters

### ISSUE THREAD

**Issue by gacopl** [kellerza/sunsynk#374]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue/bug

SENSORS_FRIST_INVERTER, impacts just reporting. 
So if I want for instance settings to be available only on Master inverter. 
Addon will produce All inverter devices with same set of entitties, just >1 inverter will show read only entities as unavailable in case of reading sensors. But in case of RW sensors they still work on the >1 inverter. 
I am able to change settings on Slave inverter even though i shouldn't

**Expected behavior**
If i populate SENSORS_FIRST_INVERTER, entities chosen in that section are present only on first inverter and addon produces devices with different entities list

### Your environment

- Home Assistant version: 2024.11.4
- Addon:
  - Name: sunsynk-multi
  - Version: 0.7.5
- Inverter:
  - Make: Deye
  - Model: 12K-SG04LP3
  - Firmware: does not matter
- Adaptor details:
  - RS485 waveshare
  -

### You configuration

```yaml

DRIVER: pymodbus
INVERTERS:
  - SERIAL_NR: "XXX"
    HA_PREFIX: DeyeM
    MODBUS_ID: 1
    DONGLE_SERIAL_NUMBER: "0"
    PORT: tcp://X:502
  - SERIAL_NR: "X"
    HA_PREFIX: DeyeS
    MODBUS_ID: 2
    DONGLE_SERIAL_NUMBER: "0"
    PORT: tcp://X:502
SENSOR_DEFINITIONS: three-phase
SENSORS:
  - energy_management
  - pv2_power
  - voltage
  - load_power
  - power_flow_card
SENSORS_FIRST_INVERTER:
  - settings
MANUFACTURER: Deye
READ_ALLOW_GAP: 6
READ_SENSORS_BATCH_SIZE: 50
SCHEDULES:
  - KEY: W
    READ_EVERY: 5
    REPORT_EVERY: 10
    CHANGE_ANY: true
    CHANGE_BY: 80
    CHANGE_PERCENT: 0
NUMBER_ENTITY_MODE: auto
PROG_TIME_INTERVAL: 15

```

### Logs

```logs

paste logs in 3x backticks...

```
