### ISSUE TITLE
Sensors ProgX Capacity missing for Deye SUN 25K HV

### ISSUE THREAD

**Issue by klacol** [kellerza/sunsynk#378]
### My environment
- Home Assistant version: 2024.12.5
- Addon:
  - Name: **multi** 
  - Version: 0.7.5
- Inverter:
  - Make: Deye SUN 25K Highvolt
  - Model: SUN-25K-SG01HP3-EU-AM2
  - Firmware: 3002-1077-1E08
- Adaptor details:
  - Waveshare USB-to-RS485 @ /dev/ttyAMA0 
  - 
### Describe the issue/bug and what you expect

I am seeking the following sensors for the HV-Battery:

```
    NumberRWSensor(166, "Prog1 Capacity", "%", min=BATTERY_LOW_CAP),
    NumberRWSensor(167, "Prog2 Capacity", "%", min=BATTERY_LOW_CAP),
    NumberRWSensor(168, "Prog3 Capacity", "%", min=BATTERY_LOW_CAP),
    NumberRWSensor(169, "Prog4 Capacity", "%", min=BATTERY_LOW_CAP),
    NumberRWSensor(170, "Prog5 Capacity", "%", min=BATTERY_LOW_CAP),
    NumberRWSensor(171, "Prog6 Capacity", "%", min=BATTERY_LOW_CAP),
```

The settings card looks like this:

![image](https://github.com/user-attachments/assets/6fa3dfb1-be42-4cab-9fda-da5bbbb7b5d5)

They seem to be included in the [three_phase_common.py](https://github.com/kellerza/sunsynk/blob/main/src/sunsynk/definitions/three_phase_common.py).  Is the three_phase_hv.py derived from the three_phase_common.py or are the sensors really missing in the three_phase_hv.py?

**Comment by klacol** [comment]
Great integration here. I will check the custom sensors and will then give feedback here.

**Comment by klacol** [comment]
I am wrong. The sensor definition was registered. Together with my prefix:

```yaml
Entity: number.deye_prog1_capacity
  Deye Prog1 Capacity

State: unknown	

Attributes:
  min: 20
  max: 100
  step: 1
  mode: auto
  unit_of_measurement: %
  icon: mdi:battery-lock
  friendly_name: Deye Prog1 Capacity
```

The state is missing, and therefore the card is complaining.
