### ISSUE TITLE
Solar export not getting set

### ISSUE THREAD

**Issue by f1wade** [kellerza/sunsynk#452]
### Issue related to

Sunsynk / mbusd Home Assistant Add-On

### Describe the issue/bug

When i switch the solar export setting even after 20 mins, ha says its on but sunsynk is still set to off.

**Expected behavior**

When solar export set to on in ha it reflects in sunsynk settings.
And updates in ha if not.

### Your environment

- Home Assistant version: 2025.1.x
- Addon:
  - Name: sunsynk-multi
  - Version: 2025-01-11
- Inverter:
  - make sunsynk 5kw
  - Model: \_\_
  - Firmware: \_\_
- Adaptor details:
  - RS485/RS232/solarman
  - RS485/RS232 brand

### You configuration

```yaml

- SERIAL_NR: "2212123089"
  HA_PREFIX: SS
  MODBUS_ID: 1
  PORT: /dev/serial/by-id/usb-FTDI_FT232R_USB_UART_A10NBOPA-if00-port0


```

```logs

18:30:23 INFO    Writing sensor solar_export=ON Registers:{247=0x00ff} 
18:45:46 INFO    Queue update solar_export=OFF
18:45:47 INFO    Writing sensor solar_export=OFF Registers:{247=0x0000} 
18:45:48 INFO    Queue update solar_export=ON
18:45:49 INFO    Writing sensor solar_export=ON Registers:{247=0x00ff} 

```

When i update the setting in sunsynk app, it updates in ha, both ways. 
When I turn it off in ha it reflects in sunsynk app.
But when I set on in ha it doesn't update in sunsynk app, and ha stays saying it's on when it's not.
