### ISSUE TITLE
V5 Modbus EXCEPTION

### ISSUE THREAD

**Issue by msaphoto06** [kellerza/sunsynk#470]
Hello,

I'm having a problem with the Docker version.
"ERROR Error reading: V5 Modbus EXCEPTION: AcknowledgeError (retry 3)"

It seems to connect but can't read.
DEYE SUN-M100G4-EU Micro Inverter

my options.yaml

```
DRIVER: solarman
INVERTERS:
  - SERIAL_NR: "XXXX"
    HA_PREFIX: DEYE
    MODBUS_ID: 1
    DONGLE_SERIAL_NUMBER: "XXXX
    PORT: tcp://192.168.0.XX:8899
SENSOR_DEFINITIONS: single-phase
SENSORS:
  - energy_management
  - power_flow_card
  - pv2_power
SENSORS_FIRST_INVERTER:
  - settings
MANUFACTURER: Deye
READ_ALLOW_GAP: 2
READ_SENSORS_BATCH_SIZE: 20
SCHEDULES:
- KEY: W
  READ_EVERY: 15
  REPORT_EVERY: 60
  CHANGE_BY: 80
- KEY: RW
  READ_EVERY: 15
  REPORT_EVERY: 60
  CHANGE_ANY: true
- KEY: any_unit
  READ_EVERY: 30
  REPORT_EVERY: 60
  CHANGE_BY: 80
NUMBER_ENTITY_MODE: "auto"
```
Thanks
