### ISSUE TITLE
Compatibility with Sunsynk 12kw 3-phase inverter?

### ISSUE THREAD

**Issue by lubster85** [kellerza/sunsynk#63]
Hi there

I recently had a Sunsynk 12kw 3-phase inverter installed, but I'm a little unsure if this integration works with this model.
I purchased a USB-RS485 cable from Solar-Assistant (https://solar-assistant.io/shop/products/sunsynk_rs485) and tried starting up the integration.

I've tried a few ports on the inverter with no success yet, but I was hoping to sense-check myself here as I don't recall the 3-phase inverter being included in the list of tested inverters.

![IMG_1743](https://user-images.githubusercontent.com/47302755/192143754-d2a43a76-ff7b-4a7f-801f-619274329656.jpg)

My understanding is that the "Meter-485" port could be used for monitoring and also the "BMS" port.

Referencing Solar Assistant, they claim there was a firmware change recently.
> The inverter manufacturer released a firmware update which changed the port to read the inverter via RS485. An RJ45 splitter can be used to allow SolarAssistant to read the inverter while the inverter is also reading a battery via CAN.

Is there perhaps something else I may be missing or should try? 
If not, I'll try find a splitter and confirm if that makes a difference.

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-09-24 08:45:31,191 INFO    Loading HASS OS configuration
2022-09-24 08:45:31,264 INFO    Filter *last used for battery_soc, total_battery_charge, total_battery_discharge, total_grid_export, total_grid_import, total_pv_power
2022-09-24 08:45:31,273 INFO    Protocol made connection.
2022-09-24 08:45:31,274 INFO    Connected to /dev/ttyUSB0
2022-09-24 08:45:41,286 ERROR   Timeout reading: 
2022-09-24 08:45:41,287 INFO    ############################################################
2022-09-24 08:45:41,287 INFO    No response on the Modbus interface, try checking the wiring to the Inverter, the USB-to-RS485 converter, etc
2022-09-24 08:45:41,287 INFO    ############################################################
2022-09-24 08:45:41,288 CRITICAL This Add-On will terminate in 30 seconds, use the Supervisor Watchdog to restart automatically.
[cmd] ./run.py exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

**Comment by kellerza** [comment]
I have no idea if this will work, have not seen any document on how to wire up the RS485 on the 12kw unit. There might even be different registers (to measure power etc on different phases etc). Would be great if you can test and report back

**Comment by lubster85** [comment]
Will certainly do so. I've ordered a splitter as I think that one "BMS" port is the one needed for communication.
Out of interest, I've seen elsewhere that when communicating over modbus, not to use Modbus SN id "00". Our inverter is configured with 00. What is the issue with using 0 as opposed to something like 1?

Yesterday I tried changing this through the Sunsynk app and shortly afterwards there was an error event with audible alert: F13: Grid_Mode_changed. I was a little taken back and changed it back to 0. Do you know if a change like this be a "real" error or is that normal behaviour for the inverter to log an event like this?

**Comment by cods4** [comment]
> Will certainly do so. I've ordered a splitter as I think that one "BMS" port is the one needed for communication. Out of interest, I've seen elsewhere that when communicating over modbus, not to use Modbus SN id "00". Our inverter is configured with 00. What is the issue with using 0 as opposed to something like 1?
> 
> Yesterday I tried changing this through the Sunsynk app and shortly afterwards there was an error event with audible alert: F13: Grid_Mode_changed. I was a little taken back and changed it back to 0. Do you know if a change like this be a "real" error or is that normal behaviour for the inverter to log an event like this?

As long as the the parallel box isn't checked (you only have the one inverter right?), Changing the Modbus SN ID to 01 wont cause any problems. The F13 error will clear after a few minutes and the inverter output will turn back on.

**Comment by kellerza** [comment]
If you have multiple inverters installed, or parallel checked, it's highly unlikely that your Modbus SN is till 0!

Modbus address 0 is a broadcast address and you are not allowed to respond to any message you receive on 0. With older firmware versions the inverter always responded...

**Comment by lubster85** [comment]
Thank you @kellerza and @cods4. Yes, only 1 x 3-phase inverter.
Will report back one I have some more info.

**Comment by sebmueller** [comment]
I have the same problem with a Deye 12kw Inverter.
Solar Assistant reads it out, but this plugin with homeassistant doesnt read.

The only one is the Serial No.

Do you have an idea?

**Comment by ronaldt80** [comment]
Planning to buy the same inverter (3fase/12kw) combined with batteries only (no solar) so very curious to hear about your progress.

Out of curiosity, with this add-on, is it possible to instruct the inverter (for instance to change discharge or charge from grid settings) or is the addon reporting state sensors only?

**Comment by cods4** [comment]
> I have the same problem with a Deye 12kw Inverter. Solar Assistant reads it out, but this plugin with homeassistant doesnt read.
> 
> The only one is the Serial No.
> 
> Do you have an idea?

The fact that it's displaying the SN means it is communicating, so that's a good start.

Have you entered the inverter SN into the config? If so, try remove the quotation marks around the serial number.

**Comment by sebmueller** [comment]
Hi,
thanks for the fast reply!

in the meanwhile, i figured out, what is the actual problem!

The Deye Sun-12k-SG04LP3 seems to "speak" another protocol.

Last night, I found another protocol description with different register addresses than the "other" one, you are using in your add on.

I tried a NodeRed Flow to read out the inverter, it worked!

I attach both documents, the old and the new one. 

[sunsynk_modbus - no chinese.docx](https://github.com/kellerza/sunsynk/files/9671512/sunsynk_modbus.-.no.chinese.docx)
[Modbus Deye amit posun.docx](https://github.com/kellerza/sunsynk/files/9671513/Modbus.Deye.amit.posun.docx)

found here, a german forum:
https://www.photovoltaikforum.com/thread/169125-answer-everything-about-deye-inverters/?pageNo=64

The Serial# registers are equal, also the Register: 02 - Communication Protocol Version.
When I read this, I get a 0x0104. What version do you get? 

Maybe, it is possible to implement both version of the protocol, switching after the read of the protocol version.

**Comment by lubster85** [comment]
I'm not sure if the same port issue exists with the 3-phase Sunsynk and Deye, but I think the port could also be the issue here. I'm waiting on a delivery for a splitter and hope to test on the "BMS" port soon.

Interestingly I also managed to connect with the inverter using NodeRed (Using "Meter-485" port) and managed to pull some values  out of it --- however the values appeared not to change over time.

As soon as I have the splitter, my plan is to first test with this integration "out the box" and see what I get. Else I'll play around more with NodeRed.

**Comment by kellerza** [comment]
@sebmueller thanks for the document. This document shows a new device type-which seems to be the 3ph inverter. So far we’ve tested the dev type 0x0300, while the 3ph is 0x0500.

The key would be to go through the new doc and map the register numbers that you are interested in. My guess is that the current implementation will either give you total(across phases) or only one of the phases, or worst case the single-phase registers will give you something entirely different.

Once we have the registers of the 3phase inverter it is possible to choose either based on the value of the device type

@sebmueller how did you connect to you inverter? (Might help @lubster85)

@ronaldt80 you can read and you can write RW type sensors.

[definitions.py](https://github.com/kellerza/sunsynk/blob/v0.2.4/sunsynk/definitions.py) will show you the registers and which are read &write — use the dev version of the addon for write

**Comment by lubster85** [comment]
I've started having a look at the doc and I can confirm that I'm getting readings that appear to be correct. I'm still going through them to work out which is which.

**Comment by ronaldt80** [comment]
Keen to hear about your experience @lubster85 and @sebmueller - my sunsynk 3ph 12kw has been ordered. I intend to switch to dynamic energy tariffs with the aim to buy low sell high :) - typically the pricing curve shows 2 peaks and 2 troughs so plenty of options to recover part of the investment. Key is however to also steer the export / import settings of the inverter - hope the r/w settings permit this

**Comment by sebmueller** [comment]
@lubster85 you are welcome.
would you also share your nodered flow?

For Overall_State - you can use register 500.

[3ph-inverter.zip](https://github.com/kellerza/sunsynk/files/9681463/3ph-inverter.zip)

@kellerza is it possible to extent your implementation to read out also the 3ph inverter?

**Comment by SimonF89** [comment]
@kellerza when do you think you will add the Deye 12kw? Depending on this, i would deside if i order the solar assistant or if i would use the home assistant :)

**Comment by lubster85** [comment]
@sebmueller i will definitely share, not a problem. Just hoping to add some of the “3-phase” metrics first and will share. 

Out of interest - I used a splitter on the “BMS” port to split readings from the inverter (based on the solar-assistant site suggestion). I have a sneaky suspicion that this was not necessary in my case (I was just referencing the incorrect registers initially). 

Would be interesting to hear how others have connected.

**Comment by jcwilson01** [comment]
@lubster85 If I am understanding it correctly, you only managed to start getting readings once you started using Node-Red? You didn't have any success using @kellerza add-on? I'm completely new to all of this and I'm also trying to get readings out of the 12kW Sunsynk without much success. I just assumed I was doing something wrong as I was getting the same error in the logs as you initially did, but I will try Node-Red and see what happens. Maybe I'm completely off-base here, but shouldn't we get something (even incorrect or 'zero' readings out of the add-on, even if the registers are different? Or did you start getting some sort of readings from the inverter when you swapped the Modbus SN to 01? I also managed to shut my inverter down by changing the SN to 01. Nearly had heart failure. But, after doing further reading, apparently you are supposed to isolate all loads from the inverter before changing anything on that settings page. Live and Learn.

**Comment by sebmueller** [comment]
@lubster85 I just used the Modbus Port. But I also read, it depends on the firmware version, which port es usable. In the future, I want to connect my diy battery, but therefore I need a converter for the battery informations.

**Comment by lubster85** [comment]
@jcwilson01, correct. This is because the integration developed by @kellerza was made-for and tested on the inverters listed here: https://github.com/kellerza/sunsynk#tested-inverters. Interestingly enough, when I changed the modbus serial id to '01', the integration picked up my inverter serial number as it started. 

I'm really no expert and I haven't looked under the hood of what this integration is doing, but I think the integration is looking for an expected response, not getting it, and safely stopping itself. If you look at the two docs that @sebmueller shared a few posts above, you'll see just how different the two are. I'm still going through it all and double-checking my initial "mappings". Once I'm done I'll share my flows (to be used at your own risk). :-)

**Comment by lubster85** [comment]
Updated addresses for 3-phase inverter "monitoring" values.

Name | 3-Phase address
-- | --
Battery_Charge_Day | 514
Battery_Charge_Volts | 606
Battery_Discharge_Day | 515
Battery_Output_Current | 591
Battery_Output_Power | 590
Battery_SoC | 588
Battery_Volts | 587
DayActive PowerWh | 501
DayReactive_PowerWh | 502
Grid_Export_Day | 521
Grid_Grid_CT | 607
Grid_Grid_Frequency | 183
Grid_Import_day | 520
Grid_Inverter_Load | 608
Grid_Phase_Voltage_A | 598
Grid_Phase_Voltage_B | 599
Grid_Phase_Voltage_C | 600
Inverter_Phase_Voltage_A | 627
Inverter_Phase_Voltage_B | 628
Inverter_Phase_Voltage_C | 629
Inverter_total_power | 636
Run_State | 500
Solar_PV_Day | 529
Solar_PV1_Amps | 677
Solar_PV1_Voltage | 676
Solar_PV2_Amps | 679
Solar_PV2_Voltage | 678
Temperature Battery | 586
Temperature DC Transformer | 540
Temperature Environment | ?
Temperature Heat Sink | 541
Total_Load | 653
Total_Load_Phase_A | 650
Total_Load_Phase_B | 651
Total_Load_Phase_C | 652

Then these are some of the "settings" addresses I can find. Most of these are R/W addresses.
Interestingly, it looks like with the single-phase inverters, it is possible to set seperate time zones for "selling" and "charging" actions. I can't find this equivalent for the 3-phase model - it looks like there is only one set of times and then all other actions hinge on those times (feel free to double-check me on this).

Name | Address
-- | --
Read_Time_Z1 | 148
Read_Time_Z2 | 149
Read_Time_Z3 | 150
Read_Time_Z4 | 151
Read_Time_Z5 | 152
Read_Time_Z6 | 153
Read_SoC_Z1 | 166
Read_SoC_Z2 | 167
Read_SoC_Z3 | 168
Read_SoC_Z4 | 169
Read_SoC_Z5 | 170
Read_SoC_Z6 | 171
Read_GC_Z1 | 172
Read_GC_Z2 | 173
Read_GC_Z3 | 174
Read_GC_Z4 | 175
Read_GC_Z5 | 176
Read_GC_Z6 | 177
Read_PL | 141
Read_UseTimer | 146
Read_SolarExport | 145
Read_LoadLimit | 142
Read_BatShut | 115
Read_BatLow | 117
Read_BatRestart | 116
Read_BatMaxC | 108
Read_BatMaxDC | 109
Read_GridEn | 130
Read_GridC | 128
Read_ExportLimit | 143
Read_SM_Z1 | 148
Read_SM_Z2 | 149
Read_SM_Z3 | 150
Read_SM_Z4 | 151
Read_SM_Z5 | 152
Read_SM_Z6 | 153

**Comment by ronaldt80** [comment]
The way i read the manual 148 - 177 should al be read/write:

 148-  153 accepts a time value, where 1745 would equate to quarter to 6.

154 - 159 should be the max watt power importing or exporting, 8000 being 8kw

160 - 165 is the voltage

166 - 171 is the target SoC level

172 - 177 is enable/disable of charge mode

Unfortunately I will only receive my deye in december.. so no possibility to test

**Comment by lubster85** [comment]
@sebmueller see attached "my" NodeRed flow. I found this at [this forum post](https://powerforum.co.za/topic/8451-sunsynk-inverter-monitoring/) and adapted it to suit my needs. Much of what I have done is stripped some functionality I didn't need/understand and I also added some of the 3-phase metrics in (as referenced in the posts above). Still very much a work in progress so please treat it with caution. :-P
[flows (Sunsynk-3ph-MQTT).json.zip](https://github.com/kellerza/sunsynk/files/9737365/flows.Sunsynk-3ph-MQTT.json.zip)


@kellerza thank you for the quick replies and apologies - you'll see the references I've posted above are based on the NodeRed flow I found (and not in line with your [definitions.py](https://github.com/kellerza/sunsynk/blob/v0.2.4/sunsynk/definitions.py)) naming. Nonetheless I hope it proves helpful if/when you consider looking at this.

In the meantime, I thought I'd share some of the Home Assistant (apexcharts) charts I've put together for our setup :-) We've been away from home so the usage is lower than normal, but its been particularly interesting seeing the usage by phase. It looks like most of our plugs + lights are on Phase A, pool pump and some other things on B and the Stove/Oven on C.

![image](https://user-images.githubusercontent.com/47302755/194647496-3c09d68b-d082-4c09-aa48-9043c8ddc44b.png)

**Comment by sebmueller** [comment]
@lubster85 thanks for sharing your flows! :)
could you also share your HA charts?

@kellerza are there some news about integrating a second set of registers in your addon? 

kind regards

**Comment by lubster85** [comment]
> @lubster85 thanks for sharing your flows! :) could you also share your HA charts?

No problem - you'll see there are a few custom cards and a theme that you'll need to download/change. I'm sure it's also not perfect, but its getting there :-)

```
views:
  - title: Inverter
    path: inverter
    theme: Mushroom
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: Energy Summary
          - square: false
            columns: 2
            type: grid
            cards:
              - type: custom:mushroom-entity-card
                name: PV
                entity: sensor.sunsynk_solar_total_power
                icon_color: '#FCCA1B'
                icon: mdi:solar-power-variant
              - type: custom:mushroom-entity-card
                name: Load
                entity: sensor.sunsynk_total_load
                icon_color: '#F78F24'
                fill_container: false
                icon: mdi:power-plug
              - type: custom:mushroom-entity-card
                name: Battery
                entity: sensor.sunsynk_battery_output_power
                icon_color: '#0B84B3'
                icon: mdi:battery-charging-100
              - type: custom:mushroom-entity-card
                name: Grid
                entity: sensor.sunsynk_grid_ct
                icon_color: '#EA285B'
                icon: mdi:transmission-tower-export
              - type: custom:mushroom-entity-card
                name: Battery
                entity: sensor.sunsynk_battery_soc
                icon_color: '#1D8D7D'
          - type: custom:apexcharts-card
            header:
              title: Overview
              show: false
              show_states: false
              colorize_states: true
            all_series_config:
              stroke_width: 2
              opacity: 0.3
              type: area
            color_list:
              - F78F24
              - 0B84B3
              - EA285B
              - FCCA1B
              - 1D8D7D
              - F39089
              - '274656'
              - 0ECAEE
              - 2BCDBC
            apex_config:
              chart:
                height: 350
                zoom:
                  type: x
                  enabled: true
                  autoScaleYaxis: true
                dropshadow:
                  enabled: false
                toolbar:
                  show: true
                  autoSelected: zoom
                xaxis.type: datetime
              stroke:
                width: 1
                curve: smooth
                opacity: 1
            yaxis:
              - id: first
                max: 100
                min: -100
                decimals: 0
                apex_config:
                  tickAmount: 4
              - id: second
                opposite: true
                decimals: 0
                apex_config:
                  tickAmount: 4
            series:
              - entity: sensor.sunsynk_total_load
                name: Tolal load
                group_by:
                  func: avg
                  duration: 10min
                yaxis_id: second
                type: area
                opacity: 0.3
              - entity: sensor.sunsynk_battery_output_power
                name: Battery output
                invert: true
                group_by:
                  func: avg
                  duration: 10min
                yaxis_id: second
                type: area
                opacity: 0.3
              - entity: sensor.sunsynk_grid_load_calc
                name: Grid
                group_by:
                  func: avg
                  duration: 10min
                yaxis_id: second
                type: area
                opacity: 0.3
              - entity: sensor.sunsynk_solar_pv1_power
                name: PV
                group_by:
                  func: avg
                  duration: 10min
                yaxis_id: second
                type: area
                opacity: 0.3
              - entity: sensor.sunsynk_battery_soc
                name: Battery %
                group_by:
                  func: avg
                  duration: 10min
                yaxis_id: first
                type: line
                opacity: 1
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: Solar production
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.sunsynk_solar_total_power
                max: 4550
                name: Solar power
                unit: W
                theme: Mushroom
                needle: true
                segments:
                  - from: 0
                    color: '#FCCA1B'
              - type: vertical-stack
                cards:
                  - type: custom:mushroom-entity-card
                    name: PV today
                    entity: sensor.sunsynk_solar_pv_day
                    icon_color: '#FCCA1B'
                    icon: mdi:solar-power-variant
                    fill_container: false
                  - type: custom:mushroom-entity-card
                    name: Green energy use
                    entity: sensor.co2_signal_grid_fossil_fuel_percentage
                    icon_color: '#1D8D7D'
                    icon: mdi:leaf-circle
          - type: custom:apexcharts-card
            header:
              title: Overview
              show: false
              show_states: false
              colorize_states: true
            all_series_config:
              stroke_width: 2
              opacity: 0.3
              type: area
            color_list:
              - FCCA1B
              - 0B84B3
              - F78F24
              - EA285B
              - 1D8D7D
              - F39089
              - '274656'
              - 0ECAEE
              - 2BCDBC
            apex_config:
              chart:
                height: 350
                zoom:
                  type: x
                  enabled: true
                  autoScaleYaxis: true
                dropshadow:
                  enabled: false
                toolbar:
                  show: false
                  autoSelected: zoom
                xaxis.type: datetime
              stroke:
                width: 2
                curve: smooth
                opacity: 1
            yaxis:
              - id: first
                max: 100
                min: -100
                decimals: 0
                apex_config:
                  tickAmount: 4
              - id: second
                opposite: true
                decimals: 0
                apex_config:
                  tickAmount: 4
            series:
              - entity: sensor.sunsynk_solar_total_power
                name: Solar production
                group_by:
                  func: avg
                  duration: 10min
                yaxis_id: second
                type: area
                opacity: 0.3
              - entity: sensor.power_production_now
                name: Estimate
                stroke_width: 5
                invert: false
                group_by:
                  func: avg
                  duration: 15min
                yaxis_id: second
                type: line
                opacity: 1
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: Load
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.sunsynk_total_load
                max: 4000
                name: Total load
                unit: W
                theme: Mushroom
                needle: true
                segments:
                  - from: 0
                    color: '#F78F24'
              - type: gauge
                entity: sensor.sunsynk_total_load_phase_a
                max: 4000
                name: Phase A
                unit: W
                theme: Mushroom
                needle: true
                segments:
                  - from: 0
                    color: '#EA285B'
          - type: horizontal-stack
            cards:
              - type: gauge
                entity: sensor.sunsynk_total_load_phase_b
                max: 4000
                name: Phase B
                unit: W
                theme: Mushroom
                needle: true
                segments:
                  - from: 0
                    color: '#FCCA1B'
              - type: gauge
                entity: sensor.sunsynk_total_load_phase_c
                max: 4000
                name: Phase C
                unit: W
                theme: Mushroom
                needle: true
                segments:
                  - from: 0
                    color: '#0B84B3'
          - type: custom:apexcharts-card
            graph_span: 24h
            update_interval: 5m
            stacked: true
            header:
              title: Load by phase
              show: false
              show_states: true
              colorize_states: true
            color_list:
              - EA285B
              - FCCA1B
              - 0B84B3
              - 1D8D7D
              - F78F24
              - F39089
              - '274656'
              - 0ECAEE
              - 2BCDBC
            apex_config:
              chart:
                height: 350
                zoom:
                  type: x
                  enabled: true
                  autoScaleYaxis: true
                dropshadow:
                  enabled: false
                toolbar:
                  show: false
                  autoSelected: zoom
                xaxis.type: datetime
              stroke:
                width: 2
                curve: smooth
                opacity: 1
            series:
              - entity: sensor.sunsynk_total_load_phase_a
                name: Phase A
                group_by:
                  func: avg
                  duration: 5min
                yaxis_id: first
                opacity: 1
                type: area
              - entity: sensor.sunsynk_total_load_phase_b
                name: Phase B
                group_by:
                  func: avg
                  duration: 5min
                yaxis_id: first
                opacity: 1
                type: area
              - entity: sensor.sunsynk_total_load_phase_c
                name: Phase C
                group_by:
                  func: avg
                  duration: 5min
                yaxis_id: first
                opacity: 1
                type: area
      - type: vertical-stack
        cards:
          - type: custom:mushroom-title-card
            title: Batteries
          - square: false
            columns: 2
            type: grid
            cards: []
          - type: gauge
            entity: sensor.sunsynk_battery_output_power
            max: 2000
            name: Battery (output)
            unit: W
            theme: Mushroom
            needle: true
            min: -2000
            segments:
              - from: -2000
                color: '#EA285B'
              - from: 0
                color: '#0B84B3'
          - type: custom:apexcharts-card
            header:
              title: Overview
              show: false
              show_states: false
              colorize_states: true
            all_series_config:
              stroke_width: 2
              opacity: 0.3
              type: area
            color_list:
              - 0B84B3
              - 1D8D7D
              - F78F24
              - EA285B
              - FCCA1B
              - F39089
              - '274656'
              - 0ECAEE
              - 2BCDBC
            apex_config:
              chart:
                height: 350
                zoom:
                  type: x
                  enabled: true
                  autoScaleYaxis: true
                dropshadow:
                  enabled: false
                toolbar:
                  show: true
                  autoSelected: zoom
                xaxis.type: datetime
              stroke:
                width: 1
                curve: smooth
                opacity: 1
            yaxis:
              - id: first
                decimals: 0
                apex_config:
                  tickAmount: 4
                min: 0
                max: 100
              - id: second
                opposite: true
                decimals: 0
                apex_config:
                  tickAmount: 4
                min: -2000
                max: 2000
            series:
              - entity: sensor.sunsynk_battery_output_power
                name: Battery output
                invert: true
                group_by:
                  func: avg
                  duration: 10min
                yaxis_id: second
                type: column
                opacity: 1
              - entity: sensor.sunsynk_battery_soc
                name: Battery %
                group_by:
                  func: avg
                  duration: 60min
                yaxis_id: first
                type: line
                opacity: 1
```
